config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #商品系のルーティング
  get '/' => 'markets#top', as: :top
  get 'markets/:id' => 'markets#details', as: :details
  get 'markets/:id/payment' => 'markets#payment', as: :payment
  post 'markets/:id/payment' => 'markets#payment_process'
  #ユーザー処理のルーティング
  get 'users/profiles' => 'users#show', as: :profile
  get 'users/profiles/edit' => 'users#edit', as: :edit
  get 'users/sign_up' => 'users#sign_up', as: :sign_up
  get 'users/sign_in' => 'users#sign_in', as: :sign_in
  get 'users/sign_out' => 'users#sign_out', as: :sign_out
  get 'users/products' => 'users#products', as: :user_product
  get 'users/products/new' => 'users#new', as: :new
  get 'users/products/:id' => 'users#product_detail', as: :product_detail
  get 'users/products/:id/edit' => 'users#product_edit', as: :product_edit
  get 'users/likes' => 'users#likes', as: :likes
  get 'users/likes/:product_id' => "users#likes_process", as: :likes_process
  post 'users/sign_up' => 'users#sign_up_process'
  post 'users/sign_in' => 'users#sign_in_process'
  post 'users/products/new' => "users#exhibit_product"
  post 'users/products/:id/edit' => "users#product_update"
  delete 'users/products/:id/destroy' => 'users#destroy_product', as: :product_destroy
  post 'users/profiles/edit' => "users#user_update"
end

app/models/user.rb
class User < ApplicationRecord
    #リレーション
    has_many :products
    has_many :user_likes
    
    has_secure_password
    #バリデーション
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name, presence: true
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
    validates :password, length: {minimum: 8}, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorize, except: [:sign_up, :sign_up_process, :sign_in, :sign_in_process]
    before_action :redirect_to_top_if_signed_in, only: [:sign_up, :sign_in]
    #プロフィールページ
    def show
        @user = User.find_by(id: current_user.id)
    end
    
    #ユーザー情報編集ページ
    def edit
        @user = User.find_by(id: current_user.id)
    end
    
    #ユーザー情報更新処理
    def user_update
        upload_file = params[:user][:image]
        #パスワード情報が入力されているか確認
        if params[:user][:password].present? and params[:user][:password_confirmation].present?
            #画像の有無をチェック
            if upload_file.present?
                #画像があるとき
                upload_file_name = upload_file.original_filename
                output_path = Rails.root.join('public', 'users') + upload_file_name
                #更新の可否
                if current_user.update(user_params.merge({image: upload_file_name}))
                    File.open(output_path, "w+b") do |f|
                        f.write(upload_file.read)
                    end
                    flash[:success] = "プロフィールを更新しました"
                    redirect_to profile_path
                else
                    flash[:danger] = "更新に失敗しました"
                    redirect_to edit_path
                end
            else
                #画像がないとき
                if current_user.update(user_params)
                    flash[:success] = "プロフィールを更新しました"
                    redirect_to profile_path
                else
                    flash[:danger] = "更新に失敗しました"
                    redirect_to edit_path
                end
            end
        else
            flash[:danger] = "パスワードが入力されていません"
            redirect_to edit_path
        end
    end
    
    #ユーザー登録ページ
    def sign_up
        @user = User.new
    end
    
    #ユーザー登録処理
    def sign_up_process
        @user = User.new(user_params)
        if @user.save
            #登録に成功したらサインインしてトップページへ
            user_sign_in(@user)
            flash[:success] = "ユーザーを登録しました。"
            redirect_to profile_path
        else
            flash[:danger] = "ユーザー登録に失敗しました"
            render sign_up_path and return
        end
    end
    
    #サインインページ
    def sign_in
        @user = User.new
    end
    
    #サインイン機能
    def sign_in_process
        @user = User.find_by(email: user_params[:email])
        #パスワード認証authenticateメソッド
        if @user && @user.authenticate(user_params[:password])
            #セッション処理
            user_sign_in(@user)
            flash[:success] = "サインインしました"
            redirect_to profile_path
        else
            if @user.nil?
                flash[:danger] = "このユーザは登録されていません"
                redirect_to sign_in_path
            else
                flash[:danger] = "サインインに失敗しました"
                render sign_in_path
            end
        end
    end
    
    #サインアウト機能
    def sign_out
        #ユーザセッションを破棄
        user_sign_out
        flash[:success] = "サインアウトしました"
        redirect_to sign_in_path
    end
    
    #出品ページ
    def new
        @product = Product.new
    end
    
    #出品情報処理
    def exhibit_product
        #画像ファイルのチェック
        upload_files = [params[:product][:image1], params[:product][:image2], params[:product][:image3]]
        #画像ファイル名の取得
        upload_files_name = Array.new
        upload_files.each do |file|
            if file.present?
                upload_files_name << file.original_filename
            else
                upload_files_name << "no_image.jpg"
            end
        end
        #画像ファイルの保存パス
        output_dir = Rails.root.join('public', 'images')
        output_pathes = Array.new
        upload_files_name.each do |name|
            output_pathes << output_dir + name
        end
        #画像ファイルの名前を追加し、Productオブジェクトを作る
        @product = Product.new(product_params.merge({image1: upload_files_name[0], image2: upload_files_name[1], image3: upload_files_name[2]}))
        
        #状態を出品中にする
        @product.status = 0
        
        #データベースに保存
        if @product.save
            #画像ファイルのアップロード
            output_pathes.each_with_index do |path, i|
            #画像ファイルがないときは処理を飛ばす
                if upload_files[i].nil?
                    next
                end
                File.open(path, "w+b") do |f|
                    f.write(upload_files[i].read)
                end
            end
            flash[:success] = "出品しました。"
            redirect_to profile_path
        else
            flash[:danger] = "出品に失敗しました"
            render "users/new" and return
        end
    end
    
    #ユーザの商品ページ
    def products
        user = User.find(current_user.id)
        @products = Product.where(user_id: user.id).page(params[:page])
    end
    
    #ユーザの商品詳細ページ
    def product_detail
        @product = Product.find_by(id: params[:id])
    end
    
    #ユーザの商品詳細編集ページ
    def product_edit
        @product = Product.find_by(id: params[:id])
    end
    
    #ユーザの商品詳細更新処理
    def product_update
        @product = Product.find_by(id: params[:id])
        #現在の画像ファイルネームを取得
        current_image_names = [@product.image1, @product.image2, @product.image3]
         #画像ファイルのチェック
        upload_files = [params[:product][:image1], params[:product][:image2], params[:product][:image3]]
        #画像更新フラグ
        img_flag = false
        #画像ファイル名の取得
        upload_files_name = Array.new
        upload_files.each_with_index do |file, i|
            if file.present?
                #画像の更新があるとき
                  upload_files_name << file.original_filename
                  img_flag = true
            else
                #画像の更新がないとき現在の画像ファイルのまま
                 upload_files_name << current_image_names[i]
            end
        end
        #画像ファイルの保存パス
        output_dir = Rails.root.join('public', 'images')
        output_pathes = Array.new
        upload_files_name.each do |name|
            output_pathes << output_dir + name
        end
        
        if img_flag
            if @product.update(product_params.merge({image1: upload_files_name[0], image2: upload_files_name[1], image3: upload_files_name[2]}))
                #画像ファイルのアップロード
                output_pathes.each_with_index do |path, i|
                #画像ファイルがないときは処理を飛ばす
                    if upload_files[i].nil?
                        next
                    end
                    File.open(path, "w+b") do |f|
                        f.write(upload_files[i].read)
                    end
                end
                flash[:notice] = "商品詳細を更新しました"
                redirect_to product_detail_path(@product)
            else
                flash[:danger] = "更新に失敗しました"
                render "users/product_edit" and return
            end
        else
            if @product.update(product_params)
                flash[:notice] = "商品詳細を更新しました"
                redirect_to product_detail_path(@product)
            else
                flash[:danger] = "更新に失敗しました"
                render "users/product_edit" and return
            end
        end
    end

    #ユーザの出品した商品削除処理
    def destroy_product
        @product = Product.find_by(id: params[:id])
        if @product.destroy
            flash[:success] = "出品した商品を削除しました"
            redirect_to user_product_path
        else
            flash[:danger] = "削除に失敗しました"
            redirect_to product_detail_path(@product)
        end
    end
    
    #お気に入りページ
    def likes
        user = User.find_by(id: current_user.id)
        @products = Product.where(id: UserLike.where(user_id: user.id).pluck(:product_id)).page(params[:page])
    end
    
    #お気に入り登録処理
    def likes_process
        product = Product.find_by(id: params[:product_id])
        #お気に入りのステータスを確認 
        if UserLike.exists?(product_id: product.id, user_id: current_user.id)
            #お気に入り削除 
            UserLike.find_by(product_id: product.id, user_id: current_user.id).destroy
        else
            #お気に入り登録
            UserLike.create(product_id: product.id, user_id: current_user.id)
        end
        redirect_to top_path and return
    end
    
    private
    def user_params
        return params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile)
    end
    
    def product_params
        return params.require(:product).permit(:name, :description, :price, :category_id).merge({user_id: current_user.id})
    end
end

app/helpers/users_helper.rb
module UsersHelper
    #渡されたユーザーでサインインする
    def user_sign_in(user)
        session[:user_id] = user.id
    end
    
    #現在サインイン中のユーザの情報を返す
    def current_user
        if @current_user.nil?
            @current_user = User.find_by(id: session[:user_id])
        else
            @current_user
        end
    end
    
    # サインアウトする
    def user_sign_out
        session.delete(:user_id)
        @current_user = nil
    end
    
    #ユーザーがサインインしていればtrue, そうでなければfalseを返す
    def user_signed_in?
        return current_user.present?
    end
    
    #認証チェック
    def authorize
        redirect_to sign_in_path unless user_signed_in?
    end
    
    #サインイン済みならトップページに遷移する
    def redirect_to_top_if_signed_in
        redirect_to top_path and return if user_signed_in?
    end
    
    #プロフィール画像がなかったらダミー画像を指定する
    def image_url(user)
        if user.image.blank?
            "https://dummyimage.com/200x200/000/fff"
        else
            "/users/#{user.image}"
        end
    end
end

app/views/users/_mypagenav.html.erb
<nav class="mypage mypage-<%= val %>">
    <%= link_to profile_path do %>
      <h1>マイページ</h1>
    <% end %>
    <ul>
      <li>
        <%= link_to('出品する', new_path) %>
      </li>
      <li>
        <%= link_to('出品中の商品', user_product_path) %>
      </li>
      <li>
        <%= link_to('お気に入りの商品', likes_path) %>
      </li>
      <li>
        <%= link_to("プロフィール更新", edit_path) %>
      </li>
      <li>
        <%= link_to('サインアウト', sign_out_path) %>
      </li>
    </ul>
</nav>

app/views/users/edit.html.erb
<div class="user_edit">
  <div class=contents>
    <div class="user_edit_form">
      <%= form_for @user, url: edit_path, method: :post do |f| %>
      <div class="user_image">
          <div style="background: url('<%= image_url(@user) %>'); background-position: 50%; background-size: cover;"></div>
      </div>
      <div>画像: <%= f.file_field :image %></div>
      <p>ニックネーム(必須)</p>
        <div class="field">
          <%= f.text_field :name, placeholder: "例) フリマ子" %>
        </div>
      <p>プロフィール</p>
        <div class="field">
          <%= f.text_area :profile, placeholder: "例) こんにちは、フリマ子です!" %>
        </div>
      <p>パスワード(必須)(更新をしない場合は現在のパスワードを入力してください)</p>
        <div class="field">
          <%= f.password_field :password, placeholder: "英数字で8文字以上" %>
        </div>
      <p>パスワード(確認用)(必須)</p>
      <div class="field">
        <%= f.password_field :password_confirmation, placeholder: "パスワード確認用" %>
      </div>
        <button>更新する</button>
      <% end %>
    </div>
  </div>
  <%= render partial: 'users/mypagenav', :locals => {:val => "user_edit"} %>
</div>

app/views/users/likes.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <div class="profile">
    <% if @products.any? %>
      <div><%= page_entries_info @products %></div>
      <% @products.each do |product| %>
      <div class="product">
        <%= link_to details_path(product) do %>
          <%= image_tag "/images/#{product.image1}" %>
        <% end %>
          <div class="product-info">
              <div class~="product-name">
                  <h1><%= product.name %></h1>
              </div>
              <div class="price">
                  <p>￥<%= product.price %></p>
              </div>
          </div>
      </div>
      <% end %>
      <div><%= paginate @products %></div>
    <% else %>
      <p>お気に入りにした商品はありません。</p>
    <% end %>
  </div>
  <%= render partial: 'users/mypagenav', :locals => {:val => "likes"} %>
</div>

app/views/users/new.html.erb
<div class="product_new user">
  <div class="contents">
    <div class="product_new_form">
      <%= form_for @product, url: new_path, method: :post do |f| %>
      <p>商品名(必須)</p>
        <div class="field">
          <%= f.text_field :name, placeholder: "コードキャンプのTシャツ" %>
        </div>
      <p>説明(必須)</p>
        <div class="field">
          <%= f.text_area :description, placeholder: "コードキャンプで作成されたオリジナルTシャツです" %>
        </div>
      <p>カテゴリー(必須)</p>
        <div class="field">
          <%= f.select :category_id, categories.map{|t| [t.name, t.id]}, :include_blank => true %>
        </div>
      <p>価格(必須)</p>
      <div class="field">
        <%= f.number_field :price, placeholder: "価格を入力してください" %>
      </div>
      <div>
        画像1
        <%= f.file_field :image1 %>
      </div>
      <div>
        画像2
        <%= f.file_field :image2 %>
      </div>
      <div>
        画像3
        <%= f.file_field :image3 %>
      </div>
        <button>送信する</button>
      <% end %>
    </div>
  </div>
  <%= render partial: 'users/mypagenav', :locals => {:val => "new"} %>
</div>

app/views/users/product_detail.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <div class="detail">
    <div class="status">
        <%= @product.status_i18n %>
    </div>
    <div class="name">
        <h1><%= @product.name %></h1>
    </div>
    <div class="image">
      <%= image_tag "/images/#{@product.image1}" %>
    </div>
    <div class="info">
      <p>カテゴリー: <%=  @product.category.name %></p>
      <div class="price">
        <h2>￥<%= @product.price %></h2>
      </div>
      <p>販売手数料(10%): ￥<%= (@product.price * 0.1).floor %></p>
      <p>販売利益: ￥<%= (@product.price * 0.9).floor %></p>
      <div class="toedit">
        <%= link_to "編集する", product_edit_path(@product) %>
      </div>
      <div class="description">
        <%= @product.description %>
      </div>
      <p class="destroy"><%= link_to "削除する", product_destroy_path(@product), method: :delete %></p>
    </div>
  </div>
  <%= render partial: 'users/mypagenav', :locals => {:val => "product_detail"} %>
</div>

app/views/users/product_edit.html.erb
<div class="product_edit user">
  <div class="contents">
    <div class="product_edit_form">
      <%= form_for @product, url: product_edit_path, method: :post do |f| %>
      <p>商品名(必須)</p>
        <div class="field">
          <%= f.text_field :name, placeholder: "コードキャンプのTシャツ" %>
        </div>
      <p>説明(必須)</p>
        <div class="field">
          <%= f.text_area :description, placeholder: "コードキャンプで作成されたオリジナルTシャツです" %>
        </div>
      <p>カテゴリー(必須)</p>
        <div class="field">
          <%= f.select :category_id, categories.map{|t| [t.name, t.id]}, :include_blank => true %>
        </div>
      <p>価格(必須)</p>
      <div class="field">
        <%= f.number_field :price, placeholder: "価格を入力してください" %>
      </div>
      <p>現在の選択中の画像</p>
      <div class="current_img">
          <%= image_tag "/images/#{@product.image1}" %>
          <%= image_tag "/images/#{@product.image2}" %>
          <%= image_tag "/images/#{@product.image3}" %>
      </div>
      <div>
        画像1
        <%= f.file_field :image1 %>
      </div>
      <div>
        画像2
        <%= f.file_field :image2 %>
      </div>
      <div>
        画像3
        <%= f.file_field :image3 %>
      </div>
        <button>更新する</button>
      <% end %>
    </div>
  </div>
  <%= render partial: 'users/mypagenav', :locals => {:val => "product_edit"} %>
</div>

app/views/users/products.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <div class="profile">
    <% if @products.any? %>
      <div><%= page_entries_info @products %></div>
      <% @products.each do |product| %>
      <div class="product">
        <%= link_to product_detail_path(product) do %>
          <%= image_tag "/images/#{product.image1}" %>
        <% end %>
          <div class="product-info">
              <div class~="product-name">
                  <h1><%= product.name %></h1>
              </div>
              <div class="price">
                  <p>￥<%= product.price %></p>
              </div>
          </div>
      </div>
      <% end %>
      <div><%= paginate @products %></div>
    <% else %>
      <p>出品中の商品はありません。</p>
    <% end %>
  </div>
  <%= render partial: 'users/mypagenav', :locals => {:val => "user_products"} %>
</div>

app/views/users/show.html.erb
<div class="user container">
  <!-- プロフィール部分 -->
  <div class="profile">
    <div class="image">
      <div style="background: url('<%= image_url(@user) %>'); background-position: 50%; background-size: cover;"></div>
    </div>
    <div class="info">
      <div class="name">
        <h1><%= @user.name %></h1>
      </div>
      <div class="status">
        <p class="posts_count">出品数:<%= @user.products.length %></p>
      </div>
      <div class="comment">
        <%= @user.profile %>
      </div>
    </div>
  </div>
  <%= render partial: 'users/mypagenav', :locals => {:val => "profile"} %>
</div>

app/views/users/sign_in.html.erb
<div class="sign_in">
  <div class="contents">
    <div class="sign_in_form">
      <%= form_for @user, url: sign_in_path do |f| %>
        <p>メールアドレス</p>
        <div class="field">
          <%= f.email_field :email, placeholder: "例) camp@exam.com" %>
        </div>
        <p>パスワード</p>
        <div class="field">
          <%= f.password_field :password, placeholder: "英数字で8文字以上" %>
        </div>
        <button>サインインする</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <p>アカウントをお持ちですか？ <%= link_to("新規登録はこちら", sign_up_path) %></p>
    </div>
  </div>
</div>

app/views/users/sign_up.html.erb
<div class="sign_up">
  <div class="contents">
    <div class="sign_up_form">
      <%= form_for @user, url: sign_up_path do |f| %>
      <p>ニックネーム</p>
        <div class="field">
          <%= f.text_field :name, placeholder: "例) フリマ子" %>
        </div>
      <p>メールアドレス</p>
        <div class="field">
          <%= f.email_field :email, placeholder: "例) camp@exam.com" %>
        </div>
      <p>パスワード</p>
        <div class="field">
          <%= f.password_field :password, placeholder: "英数字で8文字以上" %>
        </div>
      <p>パスワード(確認用)</p>
      <div class="field">
        <%= f.password_field :password_confirmation, placeholder: "パスワード確認用" %>
      </div>
        <button>登録する</button>
      <% end %>
    </div>
    <div class="sign_in_link">
      <p>アカウントをお持ちですか？ <%= link_to('サインインする', sign_in_path) %></p>
    </div>
  </div>
</div>