config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #商品系のルーティング
  get '/' => 'markets#top', as: :top
  get 'markets/:id' => 'markets#details', as: :details
  get 'markets/:id/payment' => 'markets#payment', as: :payment
  post 'markets/:id/payment' => 'markets#payment_process'
  #ユーザー処理のルーティング
  get 'users/profiles' => 'users#show', as: :profile
  get 'users/profiles/edit' => 'users#edit', as: :edit
  get 'users/sign_up' => 'users#sign_up', as: :sign_up
  get 'users/sign_in' => 'users#sign_in', as: :sign_in
  get 'users/sign_out' => 'users#sign_out', as: :sign_out
  get 'users/products' => 'users#products', as: :user_product
  get 'users/products/new' => 'users#new', as: :new
  get 'users/products/:id' => 'users#product_detail', as: :product_detail
  get 'users/products/:id/edit' => 'users#product_edit', as: :product_edit
  get 'users/likes' => 'users#likes', as: :likes
  get 'users/likes/:product_id' => "users#likes_process", as: :likes_process
  post 'users/sign_up' => 'users#sign_up_process'
  post 'users/sign_in' => 'users#sign_in_process'
  post 'users/products/new' => "users#exhibit_product"
  post 'users/products/:id/edit' => "users#product_update"
  delete 'users/products/:id/destroy' => 'users#destroy_product', as: :product_destroy
  post 'users/profiles/edit' => "users#user_update"
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
    before_action :authorize, except: [:sign_up, :sign_up_process, :sign_in, :sign_in_process]
    before_action :redirect_to_top_if_signed_in, only: [:sign_up, :sign_in]
    #商品一覧ページ
    def top
        #scopeでキーワード、カテゴリー、価格帯の検索処理を記述
        @products = Product.word_like(params[:word]).category_search(params[:category]).price_search(params[:rangemin], params[:rangemax]).page(params[:page])
        if params[:order].present?
            #並び替え
            case params[:order].to_i
            when 1
                #新しい順
                @products = @products.order("id desc")
            when 2
                #古い順
                @products = @products.order("id asc")
            when 3
                #価格の高い順
                @products = @prducts.order("price desc")
            else
                #価格の安い順
                @products = @products.order("price asc")
            end
        else
            @products = @products.order("id desc")
        end
    end
    
    #商品詳細ページ
    def details
        @product = Product.find_by(id: params[:id])
    end
    
    #商品購入確認ページ
    def payment
        @product = Product.find_by(id: params[:id])
    end
    
    #商品購入処理
    def payment_process
        product = Product.find_by(id: params[:id])
        #購入したので、状態を売り切れにする
        status = 1
        if product.update(status: status)
            flash[:success] = "商品を購入しました"
            redirect_to top_path
        else
            flash[:danger] = "購入できませんでした。"
            redirect_to payment_path(product)
        end
    end
    
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_searchform.html.erb
<nav class="searchform searchform-<%= val %>">
    <h1>詳細検索</h1>
    <%= form_tag(top_path, method: :get) do %>
        <ul>
          <li>
            キーワード追加
            <%= text_field_tag :word, params[:word], placeholder: "例)値下げ" %>
          </li>
          <li>
            カテゴリー選択
            <%= select_tag :category, options_from_collection_for_select(categories, :id, :name, params[:category]), :include_blank => true %>
          </li>
          <li>
            価格
            <div class="price_search_field">
              <%= text_field_tag :rangemin, params[:rangemin], class: "price_search" %>円
              ~
              <%= text_field_tag :rangemax, params[:rangemax], class:  "price_search" %>円
            </div>
          </li>
          <li>
            並び替え
            <%= select_tag :order, options_for_select([["新しい順", 1], ["古い順", 2], ["価格の高い順", 3], ["価格の安い順", 4]], params[:order]), :include_blank => true %>
          </li>
        </ul>
        <button>検索</button>
    <% end %>
</nav>

app/views/markets/details.html.erb
<div class="details container">
  <!-- 商品詳細部分 -->
  <div class="product-details">
    <div class="name">
        <h1><%= @product.name %></h1>
    </div>
    <div class="image">
      <%= image_tag "/images/#{@product.image1}"%>
    </div>
    <div class="info">
      <p class="product-category">カテゴリー: <%= @product.category.name %></p>
      <div class="price">
         <h2>¥.<%= @product.price %></h2>
      </div>
      <!-- 自分が出品していない商品のとき購入ボタン表示-->
      <% if @product.user_id != current_user.id %>
        <!-- 状態が出品中のときのみ表示-->
        <% if @product.status == "exhibit" %>
            <div class="topayment">
                <%= link_to "購入する", payment_path(@product) %>
            </div>
        <% end %>
      <% end %>
      <p><%= @product.description %></p> 
    </div>
  </div>
  <%= render partial: 'markets/searchform', :locals => {:val => "details"} %>
</div>

app/views/markets/payment.html.erb
<div class="details container">
  <!-- 商品詳細部分 -->
  <div class="product-details">
    <div class="name">
        <h1><%= @product.name %></h1>
    </div>
    <div class="image">
      <%= image_tag "/images/#{@product.image1}"%>
    </div>
    <div class="info">
      <div class="price">
         <h2>¥.<%= @product.price %></h2>
      </div>
      <% if @product.status == "exhibit" %>
      <div class="topayment">
          <%= link_to "購入する", payment_path(@product), method: :post %>
      </div>
      <% end %>
    </div>
  </div>
  <%= render partial: 'markets/searchform', :locals => {:val => "payment"} %>
</div>

app/views/markets/top.html.erb
<div class="list container">
  <!-- プロフィール部分 -->
  <div class="products-list">
    <% if @products.any? %>
    <div><%= page_entries_info @products %></div>
      <% @products.each do |product| %>
      <div class="product">
        <%= link_to details_path(product) do %>
          <%= image_tag "/images/#{product.image1}" %>
        <% end %>
          <div class="info">
              <div class="name">
                  <h1><%= product.name %></h1>
              </div>
              <div class="price">
                  <p>￥<%= product.price %></p>
              </div>
              <%= link_to likes_process_path(product) do %>
                <i class=" fa fa-thumbs-up <%= product.likes_from?(current_user)? "favorite" : "n-favorite" %>"></i>
              <% end %>
              <% if product.status == "soldout" %>
              <div class="status">
                  <p>SOLD</p>
              </div>
              <% end %>
          </div>
      </div>
      <% end %>
      <div><%= paginate @products %></div>
    <% else %>
      <p>対象の商品は見つかりませんでした。</p>
    <% end %>
  </div>
  <%= render partial: "markets/searchform", :locals => {:val => "top"} %>
</div>