config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #商品系のルーティング
  get '/' => 'markets#top', as: :top
  get 'markets/:id' => 'markets#details', as: :details
  get 'markets/:id/payment' => 'markets#payment', as: :payment
  post 'markets/:id/payment' => 'markets#payment_process'
  #ユーザー処理のルーティング
  get 'users/profiles' => 'users#show', as: :profile
  get 'users/profiles/edit' => 'users#edit', as: :edit
  get 'users/sign_up' => 'users#sign_up', as: :sign_up
  get 'users/sign_in' => 'users#sign_in', as: :sign_in
  get 'users/sign_out' => 'users#sign_out', as: :sign_out
  get 'users/products' => 'users#products', as: :user_product
  get 'users/products/new' => 'users#new', as: :new
  get 'users/products/:id' => 'users#product_detail', as: :product_detail
  get 'users/products/:id/edit' => 'users#product_edit', as: :product_edit
  get 'users/likes' => 'users#likes', as: :likes
  get 'users/likes/:product_id' => "users#likes_process", as: :likes_process
  post 'users/sign_up' => 'users#sign_up_process'
  post 'users/sign_in' => 'users#sign_in_process'
  post 'users/products/new' => "users#exhibit_product"
  post 'users/products/:id/edit' => "users#product_update"
  delete 'users/products/:id/destroy' => 'users#destroy_product', as: :product_destroy
  post 'users/profiles/edit' => "users#user_update"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campmarket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'%>
  </head>

  <body class="logined">
    <header class="global_header">
      <!-- ロゴ -->
      <%= link_to top_path do %>
      <div class="icon">
          <%= image_tag 'logo.png' %>
      </div>
      <% end %>
        <h1 class="logo">Market</h1>
      <!-- 検索フォーム -->
      <form class="search">
        <input type="text" placeholder="キーワードから検索                                                 &#xF002;" name="word" value="">
      </form>
      <!-- メニュー -->
      <ul class="menu">
        <li>
          <!-- 出品する -->
          <%= link_to new_path do %>
            <button>出品する</button>
          <% end %>
        </li>
        <li>
          <!-- マイページ -->
          <%= link_to profile_path do %>
            <i class="fa fa-user-circle"></i>
          <% end %>
        </li>
        <li>
          <!-- サインアウト -->
          <%= link_to sign_out_path do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </li>
      </ul>
    </header>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
      window.setTimeout(function(){
        $('.alert').slideUp();
      }, 3000);
    </script>
  </body>
</html>